# Generated by Django 4.0.4 on 2022-05-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('square_footage', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('street_address', models.TextField(max_length=255)),
                ('unit_number', models.IntegerField()),
                ('city_name', models.TextField(max_length=255)),
                ('country_or_province', models.TextField(max_length=255)),
                ('country', models.TextField(max_length=255)),
                ('warehouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('shelving_unit', models.CharField(max_length=3)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.collection')),
            ],
        ),
    ]
