# Generated by Django 4.0.4 on 2022-05-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_add_zip_code_to_address_and_warehouse_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='square_footage',
        ),
    ]
