# Generated by Django 4.0.4 on 2022-05-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_warehouse_square_footage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
