# Generated by Django 4.0.4 on 2022-05-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_product_collection_delete_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
